version: '3'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # gRPC port for the client
      - "6334:6334" # REST API port (useful for dashboard)
    volumes:
      - ./qdrant_storage:/qdrant/storage # This saves your data on your local disk